import React, { useCallback, useEffect, useState } from 'react';
import { api, setToken } from './api';

const today = new Date().toISOString().slice(0, 7);
export default function HodPanel() {
  const [rows, setRows] = useState([]); const [month, setMonth] = useState(today); const [search, setSearch] = useState(''); const [submittedSearch, setSubmittedSearch] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { try { const result = await api.get('/api/hod/outpasses', { params: { month, search: submittedSearch } }); setRows(result.data.data); } catch (error) { setMessage(error.response?.data?.message || 'Could not load requests.'); } }, [month, submittedSearch]);
  useEffect(() => { load(); }, [load]);
  const decide = async (id, action) => { const note = action === 'reject' ? window.prompt('Why is this request rejected?') : null; if (action === 'reject' && !note) return; try { await api.put(`/api/hod/outpasses/${id}/${action}`, note ? { note } : {}); setMessage(`Request ${action}ed.`); load(); } catch (error) { setMessage(error.response?.data?.message || 'Action failed.'); } };
  const pending = rows.filter((row) => row.status === 'PENDING').length;
  return <main className="page"><header className="page-head"><div><p className="eyebrow">Decision workspace</p><h1>HOD dashboard</h1><p>Only mentor-verified requests appear in this review queue.</p></div><button className="secondary" onClick={() => { setToken('HOD', null); window.location.reload(); }}>Sign out</button></header><section className="metric-grid"><article className="metric-card"><span>Requests shown</span><strong>{rows.length}</strong><small>Mentor-verified requests for this month</small></article><article className="metric-card"><span>Awaiting decision</span><strong>{pending}</strong><small>Requests that need your review</small></article></section><section className="toolbar card"><label>Month<input type="month" value={month} onChange={(e) => setMonth(e.target.value)} /></label><label>Find student<input placeholder="Name or roll number" value={search} onChange={(e) => setSearch(e.target.value)} /></label><button onClick={() => search === submittedSearch ? load() : setSubmittedSearch(search)}>Search</button></section>{message && <div className="alert">{message}</div>}<section className="card table-wrap"><div className="table-heading"><div><p className="eyebrow">Request queue</p><h2>Student outpasses</h2></div><button className="secondary" onClick={load}>Refresh</button></div><table><thead><tr><th>Student</th><th>Journey and reason</th><th>Used this month</th><th>Status</th><th>Decision</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.student.name}</strong><small>{row.student.rollNo}</small></td><td><strong>{row.destination}</strong><small>{row.reason}</small><span className="badge mentor-badge">✓ Mentor verified</span></td><td><span className={row.monthlyRequestCount >= 4 ? 'badge warning' : 'badge'}>{row.monthlyRequestCount} outpass{row.monthlyRequestCount === 1 ? '' : 'es'}</span></td><td><span className="badge">{row.status}</span></td><td>{row.status === 'PENDING' ? <div className="actions"><button onClick={() => decide(row.id, 'approve')}>Approve</button><button className="danger" onClick={() => decide(row.id, 'reject')}>Reject</button></div> : '—'}</td></tr>)}</tbody></table>{!rows.length && <p className="empty">No mentor-verified requests for this filter.</p>}</section></main>;
}
